
# -*- coding: utf-8 -*-

SERVER_HOST = "SERVER_HOST"
SERVER_PORT = 21025
USERNAME = "USERNAME"
PASSWORD = "PASSWORD"

DB_HOST = "DB_HOST"
DB_PORT = 3306
DB_USERNAME = "DB_USERNAME"
DB_PASSWORD = "DB_PASSWORD"
DB_NAME = "DB_NAME"

SCRIPT_PATH = "C:/Users/USERNAME/AppData/Local/Screeps/scripts/127.0.0.1___21025"
BRANCH_NAME = "BRANCH_NAME"
